services:
  db:
    image: mongo:latest
    container_name: zephyrus-db
    restart: always
    environment:
      MONGO_ROOT_USERNAME: admin
      MONGO_ROOT_PASSWORD: password
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"

  bot:
    build: .
    container_name: zephyrus-bot
    restart: always
    depends_on:
      - db
    env_file:
      - ./cogs/.env
    environment:
      - MONGO_URI=mongodb://admin:password@db:27017/
    volumes:
      - .:/app

  web:
    build:
      context: .
      dockerfile: ./web/node-app/Dockerfile
    container_name: zephyrus-web
    restart: always
    depends_on:
      - db
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://admin:password@db:27017/zephyrus

volumes:
  mongo_data: