apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: zephyrus-bot
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/obak41/Zephyrus.git
    targetRevision: k8s-beta
    path: ArgoCD # kustomization.yaml がこのディレクトリにあることを示します
  destination:
    server: https://kubernetes.default.svc
    namespace: zephyrus
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s