apiVersion: apps/v1
kind: Deployment
metadata:
  name: zephyrus-bot
  namespace: zephyrus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zephyrus-bot
  template:
    metadata:
      labels:
        app: zephyrus-bot
    spec:
      containers:
        - name: bot
          image: ghcr.io/penti-nameko/zephyrus-bot:v0.2
          imagePullPolicy: Always
          env:
            - name: TOKEN
              valueFrom:
                secretKeyRef:
                  name: zephyrus-secrets
                  key: TOKEN
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: zephyrus-secrets
                  key: MONGO_URI
            - name: GEMINI_API_KEY_1
              valueFrom:
                secretKeyRef:
                  name: zephyrus-secrets
                  key: GEMINI_API_KEY_1
            - name: GEMINI_API_KEY_FOR_AUTOMOD
              valueFrom:
                secretKeyRef:
                  name: zephyrus-secrets
                  key: GEMINI_API_KEY_FOR_AUTOMOD
            - name: SAFE_BROWSING_API_KEY
              valueFrom:
                secretKeyRef:
                  name: zephyrus-secrets
                  key: SAFE_BROWSING_API_KEY
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"