apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# すべてのリソースを 'zephyrus' ネームスペースにデプロイします
namespace: zephyrus

resources:
  - secret.yaml
  - mongodb.yaml
  - deployment.yaml

commonLabels:
  app.kubernetes.io/part-of: zephyrus-bot