apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  namespace: zephyrus
spec:
  ports:
    - port: 27017
  selector:
    app: mongodb
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  namespace: zephyrus
spec:
  serviceName: "mongodb-service"
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      # MongoDBのロックファイルを掃除するInitContainerを追加
      initContainers:
        - name: remove-lock-file
          image: busybox:1.28
          command:
            - sh
            - -c
            - |
              rm -f /data/db/mongod.lock
          volumeMounts:
            - name: mongo-data
              mountPath: /data/db
      containers:
        - name: mongo
          image: mongo:latest
          args: ["--wiredTigerCacheSizeGB", "0.25"]
          livenessProbe:
            tcpSocket:
              port: 27017
            initialDelaySeconds: 30  # 起動後30秒はチェックを待つ
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: 27017
            initialDelaySeconds: 15
            periodSeconds: 10
          ports:
            - containerPort: 27017
          # メモリ不足でのクラッシュ(OOM)を防ぐためにリソースを明示
          resources:
            limits:
              memory:  "2Gi"
              cpu: "500m"
            requests:
              memory: "1Gi"
              cpu: "500m"
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: zephyrus-secrets
                  key: MONGO_ROOT_USERNAME
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: zephyrus-secrets
                  key: MONGO_ROOT_PASSWORD
          volumeMounts:
            - name: mongo-data
              mountPath: /data/db
  volumeClaimTemplates:
    - metadata:
        name: mongo-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi