apiVersion: v1
data:
  GEMINI_API_KEY_1: c2FmZTtBSXphU3lBTXMxS09Yc2U3VUlLUDdOazFDYnk2ZS1RTVNNU0xEdU0=
  GEMINI_API_KEY_FOR_AUTOMOD: QUl6YVN5REVvU2F5NU9zYUxYTmt2Mk82RmlJUk11QUlLLU9qMDJR
  MONGO_ROOT_PASSWORD: YWtpYWthdHVraTEyMjc=
  MONGO_ROOT_USERNAME: Ym90
  MONGO_URI: bW9uZ29kYjovL21vbmdvZGItc2VydmljZToyNzAxNy8gIyBEb2NrZXIgQ29tcG9zZeOBp01vbmdvRELjgrXjg7zjg5PjgrnjgpLkvb/jgYbloLTlkIjjga8gbW9uZ29kYjovL2RiOjI3MDE3Lw==
  SAFE_BROWSING_API_KEY: QUl6YVN5QU1zMUtPWHNlN1VJS1A3TmsxQ2J5NmUtUU1TTVNMRHVN
  TOKEN: TVRVd01URTRPREEyTnpFME9UWXhOVE15TkEuR1YtZi13LmNDbkc0R3lHNVZBMWlfVDM1TGxEeHNZ
kind: Secret
metadata:
  name: zephyrus-secrets
  namespace: zephyrus
