apiVersion: v1
data:
  ENV_FILE_CONTENT: VE9LRU49TVRVd01URTRPREEyTnpFME9UWXhOVE15TkEuR1YtZi13LmNDbkc0R3lHNVZBMWlfVDM1TGxEeHNZCk1PTkdPX1VSST1tb25nb2RiOi8vbW9uZ29kYi1zZXJ2aWNlOjI3MDE3LyAjIERvY2tlciBDb21wb3Nl44GnTW9uZ29EQuOCteODvOODk+OCueOCkuS9v+OBhuWgtOWQiOOBryBtb25nb2RiOi8vZGI6MjcwMTcvCkdFTUlOSV9BUElfS0VZXzE9c2FmZTtBSXphU3lBTXMxS09Yc2U3VUlLUDdOazFDYnk2ZS1RTVNNU0xEdU0KR0VNSU5JX0FQSV9LRVlfRk9SX0FVVE9NT0Q9QUl6YVN5REVvU2F5NU9zYUxYTmt2Mk82RmlJUk11QUlLLU9qMDJRClNBRkVfQlJPV1NJTkdfQVBJX0tFWT1BSXphU3lBTXMxS09Yc2U3VUlLUDdOazFDYnk2ZS1RTVNNU0xEdU0K
  GEMINI_API_KEY_1: QUl6YVN5REVvU2F5NU9zYUxYTmt2Mk82RmlJUk11QUlLLU9qMDJR
  GEMINI_API_KEY_FOR_AUTOMOD: QUl6YVN5REVvU2F5NU9zYUxYTmt2Mk82RmlJUk11QUlLLU9qMDJR
  MONGO_INITDB_ROOT_PASSWORD: YWtpYWthdHVraTEyMjc=
  MONGO_INITDB_ROOT_USERNAME: Ym90
  MONGO_ROOT_PASSWORD: YWtpYWthdHVraTEyMjc=
  MONGO_URI: bW9uZ29kYjovL21vbmdvZGItc2VydmljZToyNzAxNw==
  SAFE_BROWSING_API_KEY: QUl6YVN5QU1zMUtPWHNlN1VJS1A3TmsxQ2J5NmUtUU1TTVNMRHVN
  TOKEN: TVRVd01URTRPREEyTnpFME9UWXhOVE15TkEuR1YtZi13LmNDbkc0R3lHNVZBMWlfVDM1TGxEeHNZbTg2eFo2akhaYWt2NW5V
kind: Secret
metadata:
  name: zephyrus-secrets
  namespace: zephyrus
